language: node_js
node_js: node
cache:
  directories:
    - node_modules
services: postgresql, redis
before_script:
  - sudo apt-get -qq update # qq for less output
  # - createuser root
  # - createdb codesling
install:
  - npm install
  - npm run buildEnv
  - npm run setup:rest-server & 
  - sleep 10
  - npm run setup:socket-server
  # - npm setup:services/oauth-server
  - npm run db:setup:rest-server
script:
  - npm run start & # starts all back-end servers
  - sleep 10